---
- hosts: romantic02
  become: yes
  tasks:
    - name: add firewall rule for http  and https
      firewalld:
        zone: public
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
    - name: add firewall rule for 8080-8084
      firewalld:
        port: 8080-8084/tcp
        permanent: yes
        immediate: yes
        state: enabled
    - name: forward port 443 to 8443
      firewalld:
        rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
        permanent: yes
        immediate: yes
        state: enabled

