---
- hosts: webservers
  become: yes
  tasks:
    - name: create a list of users
      user:
        name: "{{ item }}"
        state: present
        group: wheel
      with_items:
        - neneno
        - rikodo
        - yugiro
