---
- hosts: romantic02
  become: yes
  tasks:
    - name: create partitions
      parted:
        device: "{{ item }}"
        number: 1
        state: present
        part_end: 1GiB
        label: msdos
        flags: [lvm]
      loop:
        - /dev/sdb
        - /dev/sdc 
