---
- hosts: romantic02
  become: yes
  tasks:
    - name: add epel repo
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
