---
- hosts: romantic02
  become: yes
  tasks:
    - name: start and enable the httpd service using systemd
      systemd:
        name: httpd
        state: restarted
        enabled: yes
    - name: start and enable the firewalld service using systemd
      systemd:
        name: firewalld
        state: restarted
        enabled: yes
