---
- hosts: webservers
  become: yes
  tasks:
    - name: copy file
      copy:
        src: /home/r00tm4n/index.html
        dest: /var/www/html/index.html
      when: ansible_hostname == "romantic02"
