---
- name: Add or Update User Password
  hosts:  all
  become: yes
  tasks:
  - name: Change 'neneno' password
    user: 
      name: neneno
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"

