---
- name: Download Tomcat package
  hosts: localhost
  become: yes
  tasks:
  - name: Create a directory /opt/tomcat
    file:
      path: /opt/tomcat
      state: directory
      mode: 0775
      owner: root
      group: root
  - name: Download Tomcat using get_url
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.96/bin/apache-tomcat-9.0.96.tar.gz
      dest: /opt/tomcat
      mode: 0775
      group: ansible
      owner: ansible
